import { Church, Ministry, ServiceType, ServiceEvent } from './types'

// Mock data for development
export const mockChurches: Church[] = [
  {
    id: '1',
    name: 'Grace Community Church',
    address: '123 Main St, Springfield, IL 62701',
    contactEmail: 'info@gracecommunitychurch.org',
    contactPhone: '(555) 123-4567',
    timeZone: 'America/Chicago',
    primaryLanguage: 'English',
    logoUrl: '',
    isActive: true,
    accountOwnerId: 'user1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Faith Baptist Church',
    address: '456 Oak Ave, Springfield, IL 62702',
    contactEmail: 'contact@faithbaptist.org',
    contactPhone: '(555) 987-6543',
    timeZone: 'America/Chicago',
    primaryLanguage: 'English',
    logoUrl: '',
    isActive: true,
    accountOwnerId: 'user1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
]

export const mockMinistries: Ministry[] = [
  {
    id: '1',
    name: 'Worship Ministry',
    description: 'Leading the congregation in worship through music and song',
    color: '#3B82F6',
    icon: 'music',
    churchId: '1',
    leaderId: 'user2',
    isActive: true,
    displayOrder: 1,
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
  },
  {
    id: '2',
    name: 'Youth Ministry',
    description: 'Ministering to teenagers and young adults',
    color: '#EF4444',
    icon: 'users',
    churchId: '1',
    leaderId: 'user3',
    isActive: true,
    displayOrder: 2,
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
  },
  {
    id: '3',
    name: "Children's Ministry",
    description: 'Teaching and caring for children in age-appropriate ways',
    color: '#10B981',
    icon: 'baby',
    churchId: '1',
    leaderId: 'user4',
    isActive: true,
    displayOrder: 3,
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
  },
  {
    id: '4',
    name: 'Prayer Ministry',
    description: 'Dedicated to prayer and spiritual intercession',
    color: '#8B5CF6',
    icon: 'heart',
    churchId: '1',
    leaderId: 'user5',
    isActive: true,
    displayOrder: 4,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
]

export const mockServiceTypes: ServiceType[] = [
  {
    id: '1',
    name: 'Sunday Morning Service',
    description: 'Our main weekly worship service',
    defaultDayOfWeek: 0,
    defaultTime: '10:00',
    typicalDuration: 90,
    ministryId: '1',
    isActive: true,
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
  },
  {
    id: '2',
    name: 'Sunday Evening Service',
    description: 'Evening worship and fellowship',
    defaultDayOfWeek: 0,
    defaultTime: '18:00',
    typicalDuration: 75,
    ministryId: '1',
    isActive: true,
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
  },
  {
    id: '3',
    name: 'Youth Group',
    description: 'Weekly youth gathering',
    defaultDayOfWeek: 5,
    defaultTime: '19:00',
    typicalDuration: 90,
    ministryId: '2',
    isActive: true,
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
  },
  {
    id: '4',
    name: 'Wednesday Prayer Meeting',
    description: 'Midweek prayer and Bible study',
    defaultDayOfWeek: 3,
    defaultTime: '19:00',
    typicalDuration: 60,
    ministryId: '4',
    isActive: true,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
]